title: Mushroom MPPT
description: The mushroom controller, is a micropython powered mppt solar optimizer to investigate different algorithms.
theme: just-the-docs

url: https://dulouie.github.io/mushroom_mppt_doc/

# aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template

math: mathjax

# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
ga_tracking: G-CDYNG5ZVWN
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

