title: Mushroom MPPT
description: The mushroom controller, is a micropython powered mppt solar optimizer to investigate different algorithms.
theme: just-the-docs

url: https://dulouie.github.io/mushroom_mppt_doc/

# aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template

math: mathjax



